language: python
dist: xenial

# Download jadx decompiler
before_script:
  - wget https://github.com/skylot/jadx/releases/download/v1.0.0/jadx-1.0.0.zip -O /tmp/jadx-1.0.0.zip
  - unzip /tmp/jadx-1.0.0.zip -d jadx-1.0.0
  - export PATH=$PATH:$PWD/jadx-1.0.0/bin

python:
  - "3.6"
  - "3.7"
  - "3.5"
  - "3.4"
#  - "3.8-dev"  # Disabled due to LXML compile error on 3.8
# command to install dependencies
install:
  - "pip install .[tests,docs,magic]"
# command to run tests
script:
  - nosetests --with-coverage --with-timer --timer-top-n 50 --logging-level CRITICAL
  # FIXME Testing the scripts - crude ;) there should be a better way...
  - for f in $(find ./ -! -path \*signing\* -name \*.apk); do
      echo "testing $f";
      androsign $f > /dev/null || true;
      androaxml -i $f > /dev/null || true;
      androaxml -i $f -o /dev/null || true;
      androarsc -i $f > /dev/null || true;
      androarsc -i $f -o /dev/null || true;
      androarsc -i $f -t string> /dev/null || true;
      androarsc -i $f -t string -o /dev/null || true;
      done
  - python setup.py build_sphinx

after_success:
  - codecov
